/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResnetCvRouteImport } from './routes/resnet-cv'
import { Route as IndexRouteImport } from './routes/index'

const ResnetCvRoute = ResnetCvRouteImport.update({
  id: '/resnet-cv',
  path: '/resnet-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resnet-cv': typeof ResnetCvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resnet-cv': typeof ResnetCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resnet-cv': typeof ResnetCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resnet-cv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resnet-cv'
  id: '__root__' | '/' | '/resnet-cv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResnetCvRoute: typeof ResnetCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resnet-cv': {
      id: '/resnet-cv'
      path: '/resnet-cv'
      fullPath: '/resnet-cv'
      preLoaderRoute: typeof ResnetCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResnetCvRoute: ResnetCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
